print("===========================================================")
print("                 PORTAL 1 MULTIPLAYER VR")
print("                 PORTAL 1 MULTIPLAYER VR")
print("                 PORTAL 1 MULTIPLAYER VR")
print("                 PORTAL 1 MULTIPLAYER VR")
print("===========================================================")